name: PHP Composer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: wordpress_test
          MYSQL_USER: wpuser
          MYSQL_PASSWORD: wppass
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306
        options: 
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Install WP Tests
      run: bash bin/install-wp-tests.sh wordpress_test wpuser wppass 127.0.0.1 latest true
      
    - name: phpunit tests
      run: ./vendor/bin/phpunit
      env: 
        DB_PORT: ${{ job.services.mysql.ports[3306] }}
